name: Publish Map to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - name: Install packages
        run: |
        R -e "install.packages(c('googledrive', 'googlesheets4', 'httr', 'ragg', 'rvest'), repos='https://cran.rstudio.com/')"
        R -e "install.packages('tidyverse', repos='https://cran.rstudio.com/')"
          R -e "install.packages(c('rmarkdown', 'tidyverse', 'googleway'), repos='https://cran.rstudio.com/')"
          
          - name: Install pandoc
          run: |
          sudo apt-get update
          sudo apt-get install pandoc


      - name: Build Map
        run: |
          Rscript -e 'rmarkdown::render("drive_times.Rmd")'

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

